# Generated by Django 2.2.6 on 2019-11-07 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('hora_venta', models.DateField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendedor.Vendedor')),
                ('venta', models.ManyToManyField(blank=True, to='ventas.Venta')),
            ],
        ),
    ]
